const PROJECTS = [
  'hundredpercent',
  'invader',
  'mang-han-manhwa-col',
  'sns-kids',
  'kichikkochikor',
  '20000',
  'innerdemon',
  'clanet',
  'unseen',
  '23th-century',
  'dp-aksla55',
  'dolechan',
  'hh8497',
  'tan-co',
  'caronstar',
  'lahnshoong',
  'dollromancepaperdoll',
  'jeong',
  'ch-eong',
  'graycap',
  'ltr0312p-ilst',
  'hyan623',
  'nelpi-sdcharacter',
  'piter100',
  'sujan',
  'skyup920',
  'gyupg',
  'monoch',
  'parksinb-art',
  'simji',
  'precure',
  'm0ndi',
  'playlistb',
  'onceuponatime',
  'heresyinquisitor',
  'lee20522',
  'romance',
  'moonlightmemory',
  'tales-of-harmonia',
  'irontale',
  'puppet',
  'gneoneo',
  'hoinjung12',
  'klipo2002',
  'another',
  'enderwitch',
  'painpainpain',
  'halfblacksword',
  'onsf01',
  'akrmak3tp',
  'hunter',
  'zkfk900',
  'princelake',
  'danhana',
];

function useCPR(projectId) {
  return PROJECTS.includes(projectId);
}

export default useCPR;
